import React, { useState } from 'react';
import { X, Copy, Check, Download, Share2, FileText, CheckCircle2 } from 'lucide-react';

export default function DiagnosticReportModal({ isOpen, onClose, scanResult }) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !scanResult) return null;

  const generateMarkdownReport = () => {
    const vulns = scanResult.vulnerabilities || [];
    let md = `# BugIdentifier Diagnostic Security & Program Repair Report\n\n`;
    md += `**Repository / Target:** \`${scanResult.repository_url}\`\n`;
    md += `**Scan Timestamp:** ${scanResult.scan_timestamp}\n`;
    md += `**Files Scanned:** ${scanResult.files_scanned} | **Methods Sliced:** ${scanResult.methods_analyzed || vulns.length}\n`;
    md += `**Clean Methods Filtered:** ${scanResult.clean_methods_filtered || 0}\n`;
    md += `**Issues Flagged:** ${vulns.length}\n\n`;
    md += `---\n\n## Detected Defects & Suggested Repairs\n\n`;

    vulns.forEach((v, i) => {
      md += `### ${i + 1}. [${v.severity_level.toUpperCase()}] ${v.bug_type} in \`${v.file_path}\`\n`;
      md += `- **Method:** \`${v.method_name}()\` (Lines ${v.line_number_start}-${v.line_number_end})\n`;
      md += `- **Confidence:** ${Math.round((v.confidence_score || 0.9) * 100)}%\n`;
      md += `- **Matched Pattern:** \`${v.matched_historical_commit}\`\n`;
      md += `- **Pattern Commit Message:** *"${v.matched_commit_message}"*\n`;
      md += `- **Explanation:** ${v.explanation}\n\n`;
      md += `#### Suggested Refactored Patch:\n\`\`\`javascript\n${v.suggested_fix_code}\n\`\`\`\n\n`;
    });

    md += `---\n*Generated by BugIdentifier v2.0*`;
    return md;
  };

  const reportText = generateMarkdownReport();

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([reportText], { type: 'text/markdown' });
    element.href = URL.createObjectURL(file);
    element.download = `BugIdentifier_Report_${scanResult.scan_id || 'latest'}.md`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
      <div className="relative w-full max-w-2xl ui-card border border-slate-800/90 shadow-2xl overflow-hidden flex flex-col max-h-[85vh]">
        
        {/* Header */}
        <div className="p-5 border-b border-slate-800/80 flex items-center justify-between bg-[#070c17]/90">
          <div className="flex items-center space-x-3">
            <div className="p-2 rounded-xl bg-cyan-950/60 text-cyan-400 border border-cyan-800/50 shadow-[0_0_15px_rgba(6,182,212,0.2)]">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">Diagnostic Report Export</h3>
              <p className="text-xs text-slate-400">Markdown summary of detected defects and suggested repairs</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800/80 transition-all"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto flex-1 bg-[#090e1a]/95">
          <div className="bg-[#030712] p-4 rounded-xl border border-slate-800/80 font-mono text-xs text-slate-300 whitespace-pre-wrap max-h-96 overflow-y-auto leading-relaxed shadow-inner">
            {reportText}
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-800/80 bg-[#070c17]/90 flex items-center justify-between">
          <span className="text-xs text-slate-400">Export report for review or pull requests</span>
          <div className="flex items-center space-x-2.5">
            <button
              onClick={handleCopy}
              className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-slate-800/80 hover:bg-slate-700/80 text-slate-200 text-xs font-semibold border border-slate-700/80 transition-all"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4 text-slate-400" />}
              <span>{copied ? "Copied!" : "Copy"}</span>
            </button>
            <button
              onClick={handleDownload}
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white text-xs font-bold transition-all shadow-[0_0_15px_rgba(6,182,212,0.3)]"
            >
              <Download className="w-4 h-4" />
              <span>Download .md</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
